# See here the configuration file guide : https://docs.google.com/document/d/1h_R8G3NbU7CkKxMhgfCRJpF1NhTq47T2op1eVjo5SVw/edit?usp=sharing

#######################################################################################################################

#                                                    Language

#######################################################################################################################
language: "en"

fr:
  dragonStillAlive: "[Re Dragon] Un dragon est deja en vie !"
  missingMaterials: "[Re Dragon] Il vous manque des choses pour faire spawn le dragon !"
  fightStarting: "[Re Dragon] Lancement du dragon !"
  saveDone: "[Re Dragon] Sauvegarde effectuée !"
  breakInBossArea: "[Re Dragon] Hey, Vous ne pouvez pas casser de blocs ici, il n'y a pas de boss !!"
  breakInProtectedArea: "[Re Dragon] Hey, Vous ne pouvez pas casser de blocs ici !!"
  placeInBossArea: "[Re Dragon] Hey, Vous ne pouvez pas poser de blocs ici, il n'y a pas de boss !!"
  placeInProtectedArea: "[Re Dragon] Hey, Vous ne pouvez pas poser de blocs ici !!"
  placeUnAuthorizedBlock: "[Re Dragon] Hey, Vous ne pouvez pas poser ce type de blocs ici !!"
  howToUse: "[Re Dragon] Hey, utilisez /dragon pour faire spawn le dragon !!!"
  youKilledDragon: "[Re Dragon] Vous avez tue le dragon !! distribution des recompenses . ."
  youGot: "Vous avez eu : "

en:
  dragonStillAlive: "[Re Dragon] Dragon is still alive !"
  missingMaterials: "[Re Dragon] You are missing things to make the dragon spawn !"
  fightStarting: "[Re Dragon] Starting of the dragon battle !"
  saveDone: "[Re Dragon] Save performed !"
  breakInBossArea: "[Re Dragon] Hey, you can't break blocks here ! There is no boss alive !!"
  breakInProtectedArea: "[Re Dragon] Hey, you can't break blocks here !!"
  placeInBossArea: "[Re Dragon] Hey, you can't place blocks here ! There is no boss alive !!"
  placeInProtectedArea: "[Re Dragon] Hey, you can't place blocks here !!"
  placeUnAuthorizedBlock: "[Re Dragon] Hey, you can't place this type of blocks here !!"
  howToUse: "[Re Dragon] Hey, use /dragon to make the dragon spawn !!!"
  youKilledDragon: "[Re Dragon] You killed the dragon !! rewards distribution . ."
  youGot: "You got : "

tr:
  dragonStillAlive: "[Re Dragon] Ejderha hala yaşıyor !"
  missingMaterials: "[Re Dragon] Ejderhayı doğurmak için yeterli materiyellere sahip değilsin !"
  fightStarting: "[Re Dragon] Ejderha savaşı başlatılıyor !"
  saveDone: "[Re Dragon] Kaydetme başaralı !"
  breakInBossArea: "[Re Dragon] Hey, buradaki blokları kıramazsın ! Canlı bir boss yok !!"
  breakInProtectedArea: "[Re Dragon] Hey, buradaki blokları kıramazsın !!"
  placeInBossArea: "[Re Dragon] Hey, buraya blok koyamazsın ! Canlı bir boss yok !!"
  placeInProtectedArea: "[Re Dragon] Hey, buraya blok koyamazsın !!"
  placeUnAuthorizedBlock: "[Re Dragon] Hey, buraya o tür bloklar koyamazsın !!"
  howToUse: "[Re Dragon] Hey, /dragon komutunu kullanarak ejderhanın doğmasını sağlayabilirsin !!!"
  youKilledDragon: "[Re Dragon] Ejderhayı öldürdün !! ödül dağıtımı . ."
  youGot: "Kazandığın : "

#######################################################################################################################

#                                                    Plugin config

#######################################################################################################################

world: "world_the_end"

endProtectionRoots: "-200 0 -200"

endProtectionEnd: "200 200 200"

battleArenaRoots: "-50 50 -50"

battleArenaEnd: "50 110 50"

difficulties:
  easy: "200; 15"
  medium: "400; 20"
  hard: "800; 30"

required:
  easy:
    - "END_CRYSTAL 4"
  medium:
    - "END_CRYSTAL 8"
  hard:
    - "END_CRYSTAL 12"

rewards:
  easy:
    - "DRAGON_EGG; 1; 5.0; false"
  medium:
    - "DRAGON_EGG; 1; 10.0; false"
  hard:
    - "DRAGON_EGG; 1; 15.0; false"

exp:
  easy: 500
  medium: 750
  hard: 1000

spawnmethod: "1"



