name: ReusableDragon
version: 1.0.1
main: fr.shaft.reusabledragon.Main
commands:
  dragon:
    description: "Run the spawning of the ender dragon"
    permission: dragon.use
    usage: "Usage: /dragon"
  rdsave:
    description: "Save to persistent data the dragon area"
    permission: rdsave.use
    usage: "Usage: /rdsave"